name: Test Application
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    runs-on: macos-15-arm64
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Fix plugins
        run: defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES
      - run: tuist install
      - run: tuist build Self-Compiled -C Release --build-output-path ./build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Cork-build-artifacts
          path: |
            build/release/Cork.app
            !build/release/Cork.app.dSYM
          retention-days: 30
